
services:
  backend:
    hostname: backend
    restart: always
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - ./backend/app:/app/backend/app
      - ./backend/.node-persist:/app/backend/.node-persist
      - /sys/class/gpio:/sys/class/gpio
      - /:/host
    devices:
      - /dev:/dev
    pid: "host"
