
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./backend/app:/app/backend/app
      - ./backend/.node-persist:/app/backend/.node-persist
    # devices:
    #   - /dev/video0:/dev/video0
